apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: rentcom
  region: af-south-1

nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    privateNetworking: true
    iam:
      withAddonPolicies:
        albIngress: true
        autoScaler: true
        externalDNS: true
        certManager: true
