apiVersion: apps/v1
kind: Deployment
metadata:
  name: rentcom
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rentcom
  template:
    metadata:
      labels:
        app: rentcom
    spec:
      containers:
      - name: rentcom
        image: eliudnjenga/rentcom:latest 
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: password
              key: mongodb_password         

---

apiVersion: v1
kind: Service
metadata:
  name: rentcom
spec:
  type: LoadBalancer
  selector:
    app: rentcom
  ports:
  - protocol: TCP
    targetPort: 5000 # Adjust port as needed
    port: 80 # Adjust port as needed
    # Internal access to backend, adjust if needed
