apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1 # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image:  eliudnjenga/rentcom:1.0
        ports:
        - containerPort: 5000 
        env:
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: password
                key: mongodb_password
   

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
  - protocol: TCP
    targetPort: 5000 # Adjust port as needed
    port: 80 # Adjust port as needed
   # Internal access to backend, adjust if needed
